//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Movies_task2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MoviesDBEntities1 : DbContext
    {
        public MoviesDBEntities1()
            : base("name=MoviesDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Movie> Movies { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Rating> Ratings { get; set; }
    
        public virtual ObjectResult<string> AllMoviesRatedByAUser(Nullable<int> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("AllMoviesRatedByAUser", userIdParameter);
        }
    
        public virtual ObjectResult<AverageRatingOfAllMovies_Result> AverageRatingOfAllMovies()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AverageRatingOfAllMovies_Result>("AverageRatingOfAllMovies");
        }
    
        public virtual ObjectResult<Nullable<int>> AverageRatingOfAMovie(Nullable<int> movieId)
        {
            var movieIdParameter = movieId.HasValue ?
                new ObjectParameter("movieId", movieId) :
                new ObjectParameter("movieId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("AverageRatingOfAMovie", movieIdParameter);
        }
    
        public virtual int InserIntoRating(Nullable<int> userId, Nullable<int> movieId, Nullable<int> ratingNum)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(int));
    
            var movieIdParameter = movieId.HasValue ?
                new ObjectParameter("movieId", movieId) :
                new ObjectParameter("movieId", typeof(int));
    
            var ratingNumParameter = ratingNum.HasValue ?
                new ObjectParameter("RatingNum", ratingNum) :
                new ObjectParameter("RatingNum", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InserIntoRating", userIdParameter, movieIdParameter, ratingNumParameter);
        }
    
        public virtual int InsertIntoMovies(Nullable<int> movieId, string name)
        {
            var movieIdParameter = movieId.HasValue ?
                new ObjectParameter("movieId", movieId) :
                new ObjectParameter("movieId", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertIntoMovies", movieIdParameter, nameParameter);
        }
    
        public virtual int InsertIntoUser(Nullable<int> userId, Nullable<int> age, string gender, string occupation)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(int));
    
            var ageParameter = age.HasValue ?
                new ObjectParameter("age", age) :
                new ObjectParameter("age", typeof(int));
    
            var genderParameter = gender != null ?
                new ObjectParameter("gender", gender) :
                new ObjectParameter("gender", typeof(string));
    
            var occupationParameter = occupation != null ?
                new ObjectParameter("occupation", occupation) :
                new ObjectParameter("occupation", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertIntoUser", userIdParameter, ageParameter, genderParameter, occupationParameter);
        }
    
        public virtual ObjectResult<string> Top10AverageRatedMovie()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Top10AverageRatedMovie");
        }
    
        public virtual ObjectResult<string> TopAverageRatedMovie()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("TopAverageRatedMovie");
        }
    
        public virtual ObjectResult<string> WorstMovie()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("WorstMovie");
        }
    }
}
